// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations run as the privileged owner (DIRECT_URL). The app runtime uses
    // the restricted app_user via DATABASE_URL — never for DDL. DATABASE_URL is
    // the fallback so `prisma generate` etc. still work if DIRECT_URL is unset.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
